version: '3.8'

services:
  antigravity:
    image: ghcr.io/grostim/antigravity-novnc:1.2
    container_name: antigravity_browser
    shm_size: "2gb" # Recommandé pour Chromium/Electron
    ports:
      - "6901:6901" # Port noVNC (http)
      - "5901:5901" # Port VNC standard
    volumes:
      - ./work:/home/headless/Documents/work # Persistance des fichiers de travail
    environment:
      - VNC_RESOLUTION=1600x900
      # Définit le mot de passe VNC. Peut être surchargé par une variable d'environnement VNC_PW.
      - VNC_PW=${VNC_PW:-antigravity} # Mot de passe VNC par défaut
    restart: unless-stopped
